services:
  render:
    build:
      context: .
    ports:
      - "4343:4343"
    volumes:
      - ./draft:/draft:rw
      - ./serve.sh:/usr/local/bin/serve.sh:rw
    entrypoint: ["serve.sh", "/draft/draft-bensley-rpsl-exclude-members.md"]
